steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/abinaya-devops-414904/abinaya-100932542/dockerimage:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/abinaya-devops-414904/abinaya-100932542/dockerimage:$COMMIT_SHA']


options:
  # Set defaultLogsBucketBehavior to REGIONAL_USER_OWNED_BUCKET
  # defaultLogsBucket: 'gs://your-build-logs-bucket' # Replace with your build logs bucket
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'
